# Preprocessing data for predicting the election

In [1]:
#Imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
from pathlib import Path
from sklearn.preprocessing import LabelEncoder
import preprocess_predict_election as pppe


# Configuration
from preprocess_predict_election import AGE_GROUPS, EDUCATION_GROUPS, CAR_GROUP, BENEFIT_GROUP, KEEP_PARTIES
from pathlib import Path


CWD = Path.cwd()
PROJECT_ROOT = CWD.parents[2]

DEM_DATA_DIR = PROJECT_ROOT / "processed-data" / "demographics"
ELEC_DATA_DIR = PROJECT_ROOT / "processed-data" / "elections"

OUTPUT_DIR = PROJECT_ROOT / "processed-data" / "combined"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [2]:
# Getting the demografic data and conforming it into pandas dataframes.

# 2009
path = DEM_DATA_DIR / "relative_2009.csv"

df_dem_2009 = pd.read_csv(path, sep=',')

# 2013
path = DEM_DATA_DIR / "relative_2013.csv"

df_dem_2013 = pd.read_csv(path, sep=',')

# 2017 
path = DEM_DATA_DIR / "relative_2017.csv"

df_dem_2017 = pd.read_csv(path, sep=',')

# 2021 
path = DEM_DATA_DIR / "relative_2021.csv"

df_dem_2021 = pd.read_csv(path, sep=',')

In [3]:
#Normalizing income (globally/for all years) using log transform and min-max scaling to get 0-100 range
# The dict for the dfs
dfs_dict = {
    2009: df_dem_2009,
    2013: df_dem_2013,
    2017: df_dem_2017,
    2021: df_dem_2021
}


dfs_normalized = pppe.normalize_income(dfs_dict)

# Extracting back to individual variables in year df's
df_dem_2009 = dfs_normalized[2009]
df_dem_2013 = dfs_normalized[2013]
df_dem_2017 = dfs_normalized[2017]
df_dem_2021 = dfs_normalized[2021]

Global income range: 70271.51 - 1070952.00
Global log range: 11.1601 - 13.8841
Year 2009: Normalized income range 0.00 - 84.89
Year 2013: Normalized income range 9.17 - 92.16
Year 2017: Normalized income range 8.00 - 92.16
Year 2021: Normalized income range 50.28 - 100.00

In [4]:
#Preprocessing the demografic data for the question

df_dem_2009_pp = pppe.preprocess_demographics(df_dem_2009)

df_dem_2013_pp = pppe.preprocess_demographics(df_dem_2013)

df_dem_2017_pp = pppe.preprocess_demographics(df_dem_2017)

df_dem_2021_pp = pppe.preprocess_demographics(df_dem_2021)

In [5]:
# 2009
path = ELEC_DATA_DIR / "relative_2009.csv"

df_elec_2009 = pd.read_csv(path, sep=',')

# 2013
path = ELEC_DATA_DIR / "relative_2013.csv"

df_elec_2013 = pd.read_csv(path, sep=',')

# 2017 
path = ELEC_DATA_DIR / "relative_2017.csv"

df_elec_2017 = pd.read_csv(path, sep=',')

# 2021 
path = ELEC_DATA_DIR / "relative_2021.csv"

df_elec_2021 = pd.read_csv(path, sep=',')

# 2021 
path = ELEC_DATA_DIR / "relative_2025.csv"

df_elec_2025 = pd.read_csv(path, sep=',')

In [6]:
party_cols_2009 = pppe.get_party_columns(df_elec_2009, start_after='Valid votes')
party_cols_2013 = pppe.get_party_columns(df_elec_2013, start_after='Valid votes')
party_cols_2017 = pppe.get_party_columns(df_elec_2017, start_after='Valid votes')
party_cols_2021 = pppe.get_party_columns(df_elec_2021, start_after='Valid votes')
party_cols_2025 = pppe.get_party_columns(df_elec_2025, start_after='Valid votes')

print(f"Parties in 2009 {party_cols_2009}")
print(f"Parties in 2013 {party_cols_2013}")
print(f"Parties in 2017 {party_cols_2017}")
print(f"Parties in 2021 {party_cols_2021}")
print(f"Parties in 2025 {party_cols_2025}")

Parties in 2009 ['A', 'B', 'C', 'D', 'F', 'I', 'J', 'G', 'K', 'N', 'H', 'M', 'U', 'Y', 'O', 'Z', 'L', 'Q', 'R', 'V', 'P', 'E', 'Ø', 'Å', '1', '2', '3', 'T', 'Æ']
Parties in 2013 ['A', 'B', 'C', 'D', 'F', 'I', 'J', 'G', 'K', 'N', 'H', 'M', 'U', 'Y', 'O', 'Z', 'L', 'Q', 'R', 'V', 'P', 'E', 'Ø', 'Å', '01', '02', '03', '04', '05', '06', 'T', 'Æ']
Parties in 2017 ['A', 'B', 'C', 'D', 'F', 'I', 'J', 'G', 'K', 'N', 'H', 'M', 'U', 'Y', 'O', 'Z', 'L', 'Q', 'R', 'V', 'P', 'E', 'Ø', 'Å', 'T', 'Æ']
Parties in 2021 ['A', 'B', 'C', 'D', 'F', 'I', 'J', 'G', 'K', 'N', 'H', 'M', 'U', 'Y', 'O', 'Z', 'L', 'Q', 'R', 'V', 'P', 'E', 'Ø', 'Å', '0', 'T', 'Æ']
Parties in 2025 ['A', 'B', 'C', 'D', 'E', 'F', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'T', 'U', 'V', 'Y', 'Z', 'Å', 'Æ', 'Ø']

In [24]:
df_elec_2009_pp = pppe.preprocess_election(df_elec_2009)

df_elec_2013_pp = pppe.preprocess_election(df_elec_2013)

df_elec_2017_pp = pppe.preprocess_election(df_elec_2017)

df_elec_2021_pp = pppe.preprocess_election(df_elec_2021)

df_elec_2025_pp = pppe.preprocess_election(df_elec_2025)

In [8]:
winning_parties_2009 = df_elec_2009_pp["winning_party"].unique()
winning_parties_2013 = df_elec_2013_pp["winning_party"].unique()
winning_parties_2017 = df_elec_2017_pp["winning_party"].unique()
winning_parties_2021 = df_elec_2021_pp["winning_party"].unique()
winning_parties_2025 = df_elec_2025_pp["winning_party"].unique()


print(f"Winning parties in 2009 {winning_parties_2009}")
print(f"Winning parties in 2013 {winning_parties_2013}")
print(f"Winning parties in 2017 {winning_parties_2017}")
print(f"Winning parties in 2021 {winning_parties_2021}")
print(f"Winning parties in 2025 {winning_parties_2025}")

Winning parties in 2009 ['A' 'F' 'C']
Winning parties in 2013 ['A' 'Ø' 'V' 'C']
Winning parties in 2017 ['A' 'Ø' 'C']
Winning parties in 2021 ['C' 'Ø' 'A']
Winning parties in 2025 ['C' 'F' 'Ø' 'A']

### Overview of the winning parties
With both the party name and letter code

|  Party | letters |
|-------|----------|
| Socialdemokratiet | 'A' |
| Det Konservative Folkeparti | 'C' |
| SF | 'F' |
| Enhedslisten | 'Ø' |
| Venstre | 'V' |

In [9]:
#Checking how one of the data frames look:
df_elec_2021_pp

,Gruppe,Municipality,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,winning_party,winning_votes
0,101001,København,16.060790,19.598784,10.346505,8.887538,18.626140,C,19.598784
1,101002,København,15.810811,21.756757,8.963964,11.599099,15.743243,C,21.756757
2,101003,København,15.615247,18.412840,10.777976,8.437361,21.098975,Ø,21.098975
3,101005,København,18.540224,15.130527,10.828450,7.831646,21.297283,Ø,21.297283
4,101006,København,18.473547,16.493206,10.610003,8.398381,18.531367,Ø,18.531367
5,101007,København,22.101570,9.472102,10.173739,6.698964,25.526228,Ø,25.526228
6,101008,København,15.275081,13.621653,10.067667,9.243895,25.325096,Ø,25.325096
7,101009,København,14.804289,13.809585,9.830771,13.667485,17.723808,Ø,17.723808
8,101011,København,11.876739,19.045581,8.688209,8.420715,23.667879,Ø,23.667879
9,101012,København,13.066202,22.919086,8.768873,10.027100,19.337979,C,22.919086
10,101013,København,14.754532,11.314013,8.601297,6.140003,33.386264,Ø,33.386264
11,101014,København,14.358287,17.928456,9.772102,9.560432,21.823185,Ø,21.823185
12,101016,København,17.106523,12.252154,11.267606,8.696841,22.617257,Ø,22.617257
13,101017,København,17.026793,10.674157,11.581677,6.579516,26.199222,Ø,26.199222
14,101018,København,20.732830,11.931504,12.097220,7.273062,23.329037,Ø,23.329037
15,101019,København,19.840540,13.830113,13.492794,8.923643,18.981907,A,19.840540
16,101020,København,14.438046,6.269994,12.881211,4.499893,36.788228,Ø,36.788228
17,101021,København,12.461804,7.958018,12.873655,5.978477,31.845357,Ø,31.845357
18,101022,København,12.677620,9.280639,10.102131,4.973357,37.477798,Ø,37.477798
19,101023,København,12.009283,10.307484,10.868304,6.439760,32.276155,Ø,32.276155
20,101024,København,14.713265,8.457231,13.110639,5.502993,34.524039,Ø,34.524039
21,101025,København,10.812731,6.351236,13.910202,4.489912,37.198068,Ø,37.198068
22,101027,København,14.698239,7.074791,11.637309,5.125614,33.237078,Ø,33.237078
23,101028,København,24.273504,10.576923,10.982906,5.811966,24.273504,A,24.273504
24,101029,København,26.985937,10.490308,11.402509,5.321171,20.600532,A,26.985937
25,101030,København,15.978176,6.796571,11.301637,5.159782,33.359314,Ø,33.359314
26,101031,København,25.298665,16.163036,11.806044,5.305692,19.536191,A,25.298665
27,101032,København,23.835997,5.281445,10.840862,1.945796,33.425990,Ø,33.425990
28,101033,København,21.059863,13.071639,11.933268,7.242395,20.745829,A,21.059863
29,101034,København,25.805880,11.512575,12.380446,4.445625,24.796316,A,25.805880
30,101035,København,29.944253,12.052031,10.512344,4.486329,20.865410,A,29.944253
31,101036,København,30.323401,15.225291,11.155523,4.851017,17.296512,A,30.323401
32,101039,København,21.145108,14.389579,11.239018,8.664041,19.448652,A,21.145108
33,101040,København,22.521356,14.574165,11.985503,7.351799,19.466736,A,22.521356
34,101041,København,22.166428,14.820660,11.076040,8.206600,18.866571,A,22.166428
35,101042,København,20.189607,14.027388,13.061798,8.830758,18.609551,A,20.189607
36,101043,København,19.967427,13.762215,11.986971,8.745928,20.244300,Ø,20.244300
37,101044,København,22.255696,13.632084,10.807757,9.828658,16.927132,A,22.255696
38,101046,København,24.408078,12.221448,11.699164,7.694986,17.235376,A,24.408078
39,101047,København,21.815287,9.872611,11.210191,7.324841,22.866242,Ø,22.866242
40,101048,København,18.522019,14.723115,11.169911,8.977509,19.372519,Ø,19.372519
41,101049,København,14.583333,9.357345,13.541667,5.084746,33.068503,Ø,33.068503
42,101050,København,13.038455,10.777356,12.246245,6.172636,30.302030,Ø,30.302030
43,101051,København,20.893263,5.658592,9.008327,4.333838,34.121877,Ø,34.121877
44,101052,København,12.963330,11.298315,11.972250,7.532210,29.038652,Ø,29.038652
45,101053,København,14.514939,12.061970,11.656215,7.156031,27.148654,Ø,27.148654
46,101054,København,14.749536,7.003711,12.198516,6.679035,31.864564,Ø,31.864564
47,101055,København,13.710933,18.931864,7.963118,13.866603,14.704826,C,18.931864
48,101056,København,12.965799,23.141058,8.235494,13.833589,13.986728,C,23.141058
49,101058,København,12.754050,5.935199,12.945508,4.683358,36.421208,Ø,36.421208
50,101059,København,18.943914,8.054893,11.754177,4.653938,30.817422,Ø,30.817422
51,147001,Frederiksberg,15.316474,38.334048,4.972139,5.886555,19.417060,C,38.334048
52,147002,Frederiksberg,15.321477,43.077975,4.131327,6.128591,17.209302,C,43.077975
53,147003,Frederiksberg,15.967291,37.508070,5.186142,5.917796,19.604046,C,37.508070
54,147004,Frederiksberg,15.880391,39.063617,5.086967,7.052657,17.286157,C,39.063617
55,147005,Frederiksberg,20.443925,37.798546,4.802700,5.763240,17.458463,C,37.798546
56,147006,Frederiksberg,19.147440,42.473270,3.798537,5.233540,15.855374,C,42.473270
57,147007,Frederiksberg,17.304597,42.537261,4.569309,5.492968,16.499895,C,42.537261

In [25]:
df_elec_2025_pp

,Gruppe,Municipality,Matched,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,winning_party,winning_votes
0,101001,København,1,15.623180,18.156669,16.788002,7.367501,15.972627,C,18.156669
1,101002,København,1,13.283406,20.141900,15.116279,8.927868,13.716989,C,20.141900
2,101003,København,1,13.077513,15.717575,18.741366,7.029931,18.112049,F,18.741366
3,101005,København,1,14.209763,14.644756,17.883035,6.778637,18.595940,Ø,18.595940
4,101006,København,1,13.894737,15.013158,15.986842,6.605263,18.250000,Ø,18.250000
...,...,...,...,...,...,...,...,...,...,...
61,147004,Frederiksberg,1,20.431800,31.069380,8.669740,5.599910,16.552345,C,31.069380
62,147005,Frederiksberg,1,21.851805,32.368851,7.434897,4.906278,16.580702,C,32.368851
63,147006,Frederiksberg,0,22.522646,35.684875,6.533077,4.790008,15.797420,C,35.684875
64,147007,Frederiksberg,1,22.364582,35.798554,7.547888,4.871242,14.372701,C,35.798554
65,147008,Frederiksberg,1,20.078740,33.231263,8.078157,4.768154,15.850102,C,33.231263

In [ ]:
#Dropping the not matched polling areas from 2025 election data
#df_elec_2025_pp = df_elec_2025_pp[df_elec_2025_pp['Matched'] != 0]

In [20]:
df_elec_2025_pp

,Gruppe,Municipality,Matched,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,winning_party,winning_votes
0,101001,København,1,15.623180,18.156669,16.788002,7.367501,15.972627,C,18.156669
1,101002,København,1,13.283406,20.141900,15.116279,8.927868,13.716989,C,20.141900
2,101003,København,1,13.077513,15.717575,18.741366,7.029931,18.112049,F,18.741366
3,101005,København,1,14.209763,14.644756,17.883035,6.778637,18.595940,Ø,18.595940
4,101006,København,1,13.894737,15.013158,15.986842,6.605263,18.250000,Ø,18.250000
5,101007,København,1,16.681495,9.326809,17.986358,5.308422,19.543298,Ø,19.543298
6,101008,København,1,14.163004,10.207751,18.138234,5.852976,21.634039,Ø,21.634039
8,101010,København,1,13.072836,14.633606,18.297543,9.143237,15.485942,F,18.297543
9,101011,København,1,10.494162,14.349715,16.576161,6.204181,22.237307,Ø,22.237307
10,101012,København,1,12.087327,21.849485,14.288250,9.407171,15.459709,C,21.849485
11,101013,København,1,12.130866,11.101581,17.179267,5.036148,25.548340,Ø,25.548340
12,101014,København,1,11.948691,23.247232,12.528554,9.804955,13.705851,C,23.247232
13,101016,København,1,15.507736,8.483016,18.797795,5.513071,20.611773,Ø,20.611773
14,101017,København,1,12.166050,9.042335,17.975065,5.987122,23.510070,Ø,23.510070
15,101018,København,1,16.661091,10.371362,20.140515,6.908665,17.280027,F,20.140515
16,101019,København,1,14.441344,12.767371,22.067225,7.506311,15.358044,F,22.067225
17,101020,København,1,10.787402,6.358268,19.586614,3.326772,33.129921,Ø,33.129921
18,101021,København,1,7.516220,6.402252,17.982617,4.455870,31.399192,Ø,31.399192
19,101022,København,1,9.948823,8.352098,15.005118,4.278403,34.472876,Ø,34.472876
20,101023,København,1,9.501779,9.323843,18.078292,4.644128,29.323843,Ø,29.323843
21,101024,København,1,11.069718,7.752351,19.691325,4.328544,30.690083,Ø,30.690083
22,101025,København,1,7.476636,5.449520,19.744636,3.685665,35.132289,Ø,35.132289
23,101027,København,1,8.385467,5.486044,17.408566,3.392685,34.347931,Ø,34.347931
24,101028,København,1,16.582539,8.188446,17.741634,4.262479,25.200972,Ø,25.200972
25,101029,København,1,18.883249,9.407783,16.615905,4.263959,22.233503,Ø,22.233503
26,101030,København,1,9.951624,5.335176,18.023497,3.690394,32.978576,Ø,32.978576
27,101032,København,1,11.406518,2.915952,10.377358,1.715266,30.445969,Ø,30.445969
29,101034,København,1,15.865068,9.342469,21.623402,3.808143,22.703914,Ø,22.703914
30,101035,København,1,17.333333,8.965517,16.804598,3.264368,21.931034,Ø,21.931034
31,101036,København,1,19.805884,10.782530,19.502578,3.806491,18.168032,A,19.805884
32,101040,København,1,14.675085,13.073606,21.050200,6.236526,17.600862,F,21.050200
33,101041,København,1,15.921454,12.843306,19.782407,6.872761,17.686082,F,19.782407
34,101042,København,1,15.294683,12.347854,19.170404,5.605381,17.729020,F,19.170404
35,101043,København,1,13.222404,12.806418,19.878176,6.180360,19.046204,F,19.878176
36,101044,København,1,15.032941,7.646237,17.927730,6.847674,17.847874,F,17.927730
37,101046,København,1,17.870036,9.972924,18.163357,5.798736,16.538809,F,18.163357
38,101047,København,1,14.333426,8.043418,16.392986,5.538547,24.018926,Ø,24.018926
39,101048,København,1,14.240728,10.881735,18.946816,7.207838,18.299510,F,18.946816
40,101049,København,1,10.703812,9.563376,20.397524,4.415119,28.136201,Ø,28.136201
41,101050,København,1,9.773866,10.881773,19.578085,4.917286,25.163151,Ø,25.163151
42,101051,København,1,12.089899,6.690778,17.282356,3.487471,29.527254,Ø,29.527254
43,101052,København,1,9.070673,9.923947,19.569653,5.935819,26.785383,Ø,26.785383
44,101053,København,1,11.194707,11.635750,17.421196,6.952912,19.743157,Ø,19.743157
45,101054,København,1,11.396209,5.547850,17.984281,3.837263,30.073971,Ø,30.073971
46,101055,København,1,10.474421,15.418691,15.790226,9.016862,13.975422,F,15.790226
47,101056,København,1,11.528517,20.319392,15.498099,9.353612,13.825095,C,20.319392
48,101057,København,1,13.423260,8.044086,20.266491,5.412074,21.500247,Ø,21.500247
49,101058,København,1,7.862439,4.666326,17.680900,3.669138,35.310662,Ø,35.310662
50,101059,København,1,11.072144,6.312625,17.860721,3.206413,30.435872,Ø,30.435872
58,147001,Frederiksberg,1,18.582612,34.844115,8.652658,4.559813,15.231424,C,34.844115
60,147003,Frederiksberg,1,19.528410,30.507946,8.715072,5.110626,17.575569,C,30.507946
61,147004,Frederiksberg,1,20.431800,31.069380,8.669740,5.599910,16.552345,C,31.069380
62,147005,Frederiksberg,1,21.851805,32.368851,7.434897,4.906278,16.580702,C,32.368851
64,147007,Frederiksberg,1,22.364582,35.798554,7.547888,4.871242,14.372701,C,35.798554
65,147008,Frederiksberg,1,20.078740,33.231263,8.078157,4.768154,15.850102,C,33.231263

### Joining the election data with the demographic data

And saving them as csv's

In [11]:
# 2009

joined_df_2009 = pd.merge(df_elec_2009_pp, df_dem_2009_pp, on='Gruppe', how='inner')

joined_df_2009.to_csv(OUTPUT_DIR / "pp_combined_2009.csv", index=False)

In [12]:
# 2013

joined_df_2013 = pd.merge(df_elec_2013_pp, df_dem_2013_pp, on='Gruppe', how='inner')

joined_df_2013.to_csv(OUTPUT_DIR / "pp_combined_2013.csv", index=False)

In [13]:
# 2017

joined_df_2017 = pd.merge(df_elec_2017_pp, df_dem_2017_pp, on='Gruppe', how='inner')

joined_df_2017.to_csv(OUTPUT_DIR / "pp_combined_2017.csv", index=False)

In [14]:
# 2021

joined_df_2021 = pd.merge(df_elec_2021_pp, df_dem_2021_pp, on='Gruppe', how='inner')

joined_df_2021.to_csv(OUTPUT_DIR / "pp_combined_2021.csv", index=False)

### Saving the preprocessed 2025 election data

In [32]:
joined_df_2021_dem_2025_elec = pd.merge(df_elec_2025_pp, df_dem_2021_pp, on='Gruppe', how='inner')

In [33]:
joined_df_2021_dem_2025_elec

,Gruppe,Municipality,Matched,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,winning_party,winning_votes,...,Income_Median_normalized,Children_0_17,Youth_18_29,WorkingAge_30_64,Seniors_65_plus,Education_Long_higher_education,Education_Primary_lower_secondary,Education_Vocational_training,Households_with_car,People_on_benefits
0,101001,København,1,15.623180,18.156669,16.788002,7.367501,15.972627,C,18.156669,...,71.385246,16.533865,26.018507,45.836011,11.611618,37.800951,10.259163,12.544088,37.145699,3.232232
1,101002,København,1,13.283406,20.141900,15.116279,8.927868,13.716989,C,20.141900,...,69.726746,16.782048,21.986154,44.127477,17.104321,34.531653,12.918934,14.866800,44.521982,4.105992
2,101003,København,1,13.077513,15.717575,18.741366,7.029931,18.112049,F,18.741366,...,75.051252,19.222517,22.523034,47.248517,11.005932,40.057727,9.563929,11.506358,39.805953,2.189827
3,101005,København,1,14.209763,14.644756,17.883035,6.778637,18.595940,Ø,18.595940,...,67.236974,15.529204,26.510660,44.152895,13.807241,30.339084,13.838489,16.418798,35.995702,4.352214
4,101006,København,1,13.894737,15.013158,15.986842,6.605263,18.250000,Ø,18.250000,...,68.155969,16.690146,25.950916,44.479870,12.879069,31.825453,13.917526,16.743690,38.789585,5.034478
5,101007,København,1,16.681495,9.326809,17.986358,5.308422,19.543298,Ø,19.543298,...,63.950418,18.703120,21.079565,45.222573,14.994742,19.546082,22.877114,23.136003,41.332771,7.584998
6,101008,København,1,14.163004,10.207751,18.138234,5.852976,21.634039,Ø,21.634039,...,100.000000,17.899712,23.553191,48.485569,10.061528,31.835475,13.868351,16.757591,40.116938,5.050085
7,101009,København,0,12.635507,9.952017,14.963569,8.690243,18.873289,Ø,18.873289,...,97.406394,20.945206,29.985191,42.769300,6.300303,28.984615,13.308718,15.577436,40.041128,3.319168
8,101011,København,1,10.494162,14.349715,16.576161,6.204181,22.237307,Ø,22.237307,...,75.211873,12.695361,30.666075,47.231672,9.406892,36.993384,13.887808,9.996108,33.907904,6.152936
9,101012,København,1,12.087327,21.849485,14.288250,9.407171,15.459709,C,21.849485,...,81.619269,18.962511,19.158675,46.120314,15.758500,42.801868,8.819213,10.433622,50.460271,1.514821
10,101013,København,1,12.130866,11.101581,17.179267,5.036148,25.548340,Ø,25.548340,...,71.685213,15.414302,21.415059,46.265607,16.905032,36.524509,12.086356,12.838436,40.444848,3.458191
11,101014,København,1,11.948691,23.247232,12.528554,9.804955,13.705851,C,23.247232,...,72.329061,12.456623,28.562881,43.029795,15.950700,38.508321,9.302947,10.900221,39.211689,2.010291
12,101016,København,1,15.507736,8.483016,18.797795,5.513071,20.611773,Ø,20.611773,...,68.384013,15.716445,28.582223,44.676467,11.024866,26.467441,16.753108,19.058204,35.778602,4.519852
13,101017,København,1,12.166050,9.042335,17.975065,5.987122,23.510070,Ø,23.510070,...,64.690770,13.711595,33.490268,44.711935,8.086201,27.663249,15.678627,17.433697,30.221263,5.989419
14,101018,København,1,16.661091,10.371362,20.140515,6.908665,17.280027,F,20.140515,...,67.497959,16.744969,25.237124,47.460332,10.557575,23.262456,15.349624,24.066434,41.716329,4.272671
15,101019,København,1,14.441344,12.767371,22.067225,7.506311,15.358044,F,22.067225,...,76.215537,22.009283,19.059739,48.225782,10.705195,28.318584,13.702541,20.877343,53.735060,3.099266
16,101020,København,1,10.787402,6.358268,19.586614,3.326772,33.129921,Ø,33.129921,...,62.065578,16.976388,25.010931,45.507215,12.505466,34.704572,17.188524,12.694878,25.846341,7.345868
17,101021,København,1,7.516220,6.402252,17.982617,4.455870,31.399192,Ø,31.399192,...,58.381641,12.646353,41.262454,40.549778,5.541415,35.340795,13.331106,10.808553,23.528649,6.639517
18,101022,København,1,9.948823,8.352098,15.005118,4.278403,34.472876,Ø,34.472876,...,70.429722,18.310818,24.667953,46.418436,10.602793,33.569001,15.785180,12.222978,31.763827,6.731752
19,101023,København,1,9.501779,9.323843,18.078292,4.644128,29.323843,Ø,29.323843,...,70.413149,16.060961,31.311947,45.092188,7.534904,41.852037,9.360160,9.935016,29.075738,3.282532
20,101024,København,1,11.069718,7.752351,19.691325,4.328544,30.690083,Ø,30.690083,...,69.601739,18.524820,25.690552,49.119295,6.665332,36.067581,13.467189,13.675318,33.075799,5.794636
21,101025,København,1,7.476636,5.449520,19.744636,3.685665,35.132289,Ø,35.132289,...,66.385361,15.303374,32.293734,46.179473,6.223419,37.779260,12.762588,11.195398,26.917189,5.628012
22,101027,København,1,8.385467,5.486044,17.408566,3.392685,34.347931,Ø,34.347931,...,61.497342,13.049285,36.127186,44.248013,6.575517,27.284614,16.395467,14.731948,28.033522,8.241653
23,101028,København,1,16.582539,8.188446,17.741634,4.262479,25.200972,Ø,25.200972,...,60.865467,17.353437,20.059936,46.150965,16.435662,22.697109,20.368912,20.807558,40.088731,8.428545
24,101029,København,1,18.883249,9.407783,16.615905,4.263959,22.233503,Ø,22.233503,...,61.791442,17.516340,23.970588,43.218954,15.294118,20.500197,20.539583,21.721150,38.466315,8.758170
25,101030,København,1,9.951624,5.335176,18.023497,3.690394,32.978576,Ø,32.978576,...,63.045428,12.488167,37.042161,44.454962,6.014709,27.915077,16.354288,14.795157,28.124138,8.279327
26,101032,København,1,11.406518,2.915952,10.377358,1.715266,30.445969,Ø,30.445969,...,58.083065,28.937184,19.738017,42.185174,9.139625,12.104937,35.302623,19.355505,42.643678,11.655255
27,101033,København,0,14.869436,12.352862,20.173184,5.330808,19.672575,F,20.173184,...,69.220655,18.166468,24.016687,45.093365,12.723480,27.141979,14.419176,20.172096,45.937873,4.410012
28,101034,København,1,15.865068,9.342469,21.623402,3.808143,22.703914,Ø,22.703914,...,70.136446,22.873182,19.331120,45.232448,12.563251,24.490632,17.231494,20.088052,50.621670,6.586022
29,101035,København,1,17.333333,8.965517,16.804598,3.264368,21.931034,Ø,21.931034,...,62.611108,21.432749,18.226121,44.571150,15.769981,17.529339,25.052502,22.767140,46.146024,9.249513
30,101036,København,1,19.805884,10.782530,19.502578,3.806491,18.168032,A,19.805884,...,71.705296,22.852370,15.367483,47.271715,14.508431,20.383743,21.394677,23.839488,58.065735,6.092905
31,101040,København,1,14.675085,13.073606,21.050200,6.236526,17.600862,F,21.050200,...,82.869228,24.222896,17.639626,46.525145,11.612333,27.937990,12.618770,20.503417,63.820739,2.312358
32,101041,København,1,15.921454,12.843306,19.782407,6.872761,17.686082,F,19.782407,...,67.483998,17.722591,22.442500,45.957387,13.877522,24.034518,15.746753,20.121326,43.264809,5.707634
33,101042,København,1,15.294683,12.347854,19.170404,5.605381,17.729020,F,19.170404,...,72.107979,21.260440,21.268877,45.634017,11.836666,26.666667,15.551983,20.171490,49.806094,4.640175
34,101043,København,1,13.222404,12.806418,19.878176,6.180360,19.046204,F,19.878176,...,69.101228,14.375673,30.789626,45.273014,9.561687,28.150289,13.564547,18.342967,38.429420,4.018560
35,101044,København,1,15.032941,7.646237,17.927730,6.847674,17.847874,F,17.927730,...,68.834292,20.284091,26.477273,43.948864,9.289773,19.945491,21.147175,21.271060,44.872847,7.433712
36,101046,København,1,17.870036,9.972924,18.163357,5.798736,16.538809,F,18.163357,...,65.211558,18.034743,25.964726,45.192945,10.807585,17.051365,23.862159,22.578023,45.494505,8.871502
37,101047,København,1,14.333426,8.043418,16.392986,5.538547,24.018926,Ø,24.018926,...,67.129204,21.347064,20.957417,43.960479,13.735040,22.790449,22.683535,18.692088,40.114527,7.598107
38,101048,København,1,14.240728,10.881735,18.946816,7.207838,18.299510,F,18.946816,...,71.613979,18.621000,30.473186,43.893646,7.012168,28.689976,13.421111,16.685107,38.505961,4.596665
39,101049,København,1,10.703812,9.563376,20.397524,4.415119,28.136201,Ø,28.136201,...,73.887527,20.065140,21.407422,52.842479,5.684959,38.030602,11.685587,12.524679,33.918009,3.375444
40,101050,København,1,9.773866,10.881773,19.578085,4.917286,25.163151,Ø,25.163151,...,72.782599,17.651567,25.391689,51.311308,5.645436,37.791538,11.857585,11.589267,31.881777,4.359673
41,101051,København,1,12.089899,6.690778,17.282356,3.487471,29.527254,Ø,29.527254,...,59.195212,14.998340,21.970452,49.584993,13.446215,18.455103,26.296332,22.006032,30.681983,11.777888
42,101052,København,1,9.070673,9.923947,19.569653,5.935819,26.785383,Ø,26.785383,...,76.378592,17.369727,24.554968,51.785522,6.289783,39.722834,10.879420,10.180028,32.076339,3.355270
43,101053,København,1,11.194707,11.635750,17.421196,6.952912,19.743157,Ø,19.743157,...,76.527024,20.727933,19.361725,52.182730,7.727612,38.506449,13.890020,12.070604,37.650602,3.885153
44,101054,København,1,11.396209,5.547850,17.984281,3.837263,30.073971,Ø,30.073971,...,50.278649,10.854969,34.914951,44.471799,9.758281,25.872383,18.843470,15.852443,20.493359,10.519248
45,101055,København,1,10.474421,15.418691,15.790226,9.016862,13.975422,F,15.790226,...,85.072345,15.559530,36.394992,45.088145,2.957333,39.140433,7.089049,11.505828,44.408523,1.520184
46,101056,København,1,11.528517,20.319392,15.498099,9.353612,13.825095,C,20.319392,...,81.098563,17.820669,22.299260,50.173335,9.706737,41.658055,8.439545,13.365484,44.258598,2.286143
47,101058,København,1,7.862439,4.666326,17.680900,3.669138,35.310662,Ø,35.310662,...,66.064343,17.941567,33.094290,43.505976,5.458167,29.734987,17.051625,12.197099,29.650679,8.492696
48,101059,København,1,11.072144,6.312625,17.860721,3.206413,30.435872,Ø,30.435872,...,63.178102,19.613787,25.036488,45.335130,10.014595,20.958923,23.033787,19.304640,37.768849,8.701022
49,147001,Frederiksberg,1,18.582612,34.844115,8.652658,4.559813,15.231424,C,34.844115,...,80.281516,20.860955,15.649912,46.656038,16.833096,38.131845,11.457456,14.374473,52.548876,3.121591
50,147002,Frederiksberg,0,20.515280,37.371523,7.729204,4.865013,13.800192,C,37.371523,...,79.612367,18.929174,15.185497,46.500843,19.384486,38.650752,10.534510,15.256876,53.802817,2.588533
51,147003,Frederiksberg,1,19.528410,30.507946,8.715072,5.110626,17.575569,C,30.507946,...,76.598552,18.400152,21.303768,46.190991,14.105089,38.524909,9.963472,13.942644,44.676782,2.344495
52,147004,Frederiksberg,1,20.431800,31.069380,8.669740,5.599910,16.552345,C,31.069380,...,72.171752,18.372667,23.737651,42.508233,15.381449,35.366261,11.930586,14.725513,44.254974,3.835071
53,147005,Frederiksberg,1,21.851805,32.368851,7.434897,4.906278,16.580702,C,32.368851,...,64.543385,16.898845,22.247112,44.102205,16.751838,26.712216,17.772473,18.184063,39.877691,7.917396
54,147006,Frederiksberg,0,22.522646,35.684875,6.533077,4.790008,15.797420,C,35.684875,...,66.271451,15.612127,20.670621,39.479321,24.237930,25.449946,15.439245,22.492460,44.937276,4.588894
55,147007,Frederiksberg,1,22.364582,35.798554,7.547888,4.871242,14.372701,C,35.798554,...,96.603746,15.628415,22.770071,45.384615,16.216898,33.982791,12.056176,16.655128,42.826688,3.997478

In [34]:
joined_df_2021_dem_2025_elec = joined_df_2021_dem_2025_elec.drop('Matched', axis=1)

In [35]:
joined_df_2021_dem_2025_elec

,Gruppe,Municipality,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,winning_party,winning_votes,Sex_Female,...,Income_Median_normalized,Children_0_17,Youth_18_29,WorkingAge_30_64,Seniors_65_plus,Education_Long_higher_education,Education_Primary_lower_secondary,Education_Vocational_training,Households_with_car,People_on_benefits
0,101001,København,15.623180,18.156669,16.788002,7.367501,15.972627,C,18.156669,52.891659,...,71.385246,16.533865,26.018507,45.836011,11.611618,37.800951,10.259163,12.544088,37.145699,3.232232
1,101002,København,13.283406,20.141900,15.116279,8.927868,13.716989,C,20.141900,53.354022,...,69.726746,16.782048,21.986154,44.127477,17.104321,34.531653,12.918934,14.866800,44.521982,4.105992
2,101003,København,13.077513,15.717575,18.741366,7.029931,18.112049,F,18.741366,51.785940,...,75.051252,19.222517,22.523034,47.248517,11.005932,40.057727,9.563929,11.506358,39.805953,2.189827
3,101005,København,14.209763,14.644756,17.883035,6.778637,18.595940,Ø,18.595940,51.759808,...,67.236974,15.529204,26.510660,44.152895,13.807241,30.339084,13.838489,16.418798,35.995702,4.352214
4,101006,København,13.894737,15.013158,15.986842,6.605263,18.250000,Ø,18.250000,51.605249,...,68.155969,16.690146,25.950916,44.479870,12.879069,31.825453,13.917526,16.743690,38.789585,5.034478
5,101007,København,16.681495,9.326809,17.986358,5.308422,19.543298,Ø,19.543298,51.139152,...,63.950418,18.703120,21.079565,45.222573,14.994742,19.546082,22.877114,23.136003,41.332771,7.584998
6,101008,København,14.163004,10.207751,18.138234,5.852976,21.634039,Ø,21.634039,51.050739,...,100.000000,17.899712,23.553191,48.485569,10.061528,31.835475,13.868351,16.757591,40.116938,5.050085
7,101009,København,12.635507,9.952017,14.963569,8.690243,18.873289,Ø,18.873289,49.723134,...,97.406394,20.945206,29.985191,42.769300,6.300303,28.984615,13.308718,15.577436,40.041128,3.319168
8,101011,København,10.494162,14.349715,16.576161,6.204181,22.237307,Ø,22.237307,46.191392,...,75.211873,12.695361,30.666075,47.231672,9.406892,36.993384,13.887808,9.996108,33.907904,6.152936
9,101012,København,12.087327,21.849485,14.288250,9.407171,15.459709,C,21.849485,51.710985,...,81.619269,18.962511,19.158675,46.120314,15.758500,42.801868,8.819213,10.433622,50.460271,1.514821
10,101013,København,12.130866,11.101581,17.179267,5.036148,25.548340,Ø,25.548340,50.192963,...,71.685213,15.414302,21.415059,46.265607,16.905032,36.524509,12.086356,12.838436,40.444848,3.458191
11,101014,København,11.948691,23.247232,12.528554,9.804955,13.705851,C,23.247232,51.334211,...,72.329061,12.456623,28.562881,43.029795,15.950700,38.508321,9.302947,10.900221,39.211689,2.010291
12,101016,København,15.507736,8.483016,18.797795,5.513071,20.611773,Ø,20.611773,51.442506,...,68.384013,15.716445,28.582223,44.676467,11.024866,26.467441,16.753108,19.058204,35.778602,4.519852
13,101017,København,12.166050,9.042335,17.975065,5.987122,23.510070,Ø,23.510070,51.075086,...,64.690770,13.711595,33.490268,44.711935,8.086201,27.663249,15.678627,17.433697,30.221263,5.989419
14,101018,København,16.661091,10.371362,20.140515,6.908665,17.280027,F,20.140515,49.880330,...,67.497959,16.744969,25.237124,47.460332,10.557575,23.262456,15.349624,24.066434,41.716329,4.272671
15,101019,København,14.441344,12.767371,22.067225,7.506311,15.358044,F,22.067225,49.925138,...,76.215537,22.009283,19.059739,48.225782,10.705195,28.318584,13.702541,20.877343,53.735060,3.099266
16,101020,København,10.787402,6.358268,19.586614,3.326772,33.129921,Ø,33.129921,52.787495,...,62.065578,16.976388,25.010931,45.507215,12.505466,34.704572,17.188524,12.694878,25.846341,7.345868
17,101021,København,7.516220,6.402252,17.982617,4.455870,31.399192,Ø,31.399192,51.138099,...,58.381641,12.646353,41.262454,40.549778,5.541415,35.340795,13.331106,10.808553,23.528649,6.639517
18,101022,København,9.948823,8.352098,15.005118,4.278403,34.472876,Ø,34.472876,51.367919,...,70.429722,18.310818,24.667953,46.418436,10.602793,33.569001,15.785180,12.222978,31.763827,6.731752
19,101023,København,9.501779,9.323843,18.078292,4.644128,29.323843,Ø,29.323843,51.966322,...,70.413149,16.060961,31.311947,45.092188,7.534904,41.852037,9.360160,9.935016,29.075738,3.282532
20,101024,København,11.069718,7.752351,19.691325,4.328544,30.690083,Ø,30.690083,51.591273,...,69.601739,18.524820,25.690552,49.119295,6.665332,36.067581,13.467189,13.675318,33.075799,5.794636
21,101025,København,7.476636,5.449520,19.744636,3.685665,35.132289,Ø,35.132289,51.552311,...,66.385361,15.303374,32.293734,46.179473,6.223419,37.779260,12.762588,11.195398,26.917189,5.628012
22,101027,København,8.385467,5.486044,17.408566,3.392685,34.347931,Ø,34.347931,49.723370,...,61.497342,13.049285,36.127186,44.248013,6.575517,27.284614,16.395467,14.731948,28.033522,8.241653
23,101028,København,16.582539,8.188446,17.741634,4.262479,25.200972,Ø,25.200972,49.719049,...,60.865467,17.353437,20.059936,46.150965,16.435662,22.697109,20.368912,20.807558,40.088731,8.428545
24,101029,København,18.883249,9.407783,16.615905,4.263959,22.233503,Ø,22.233503,51.519608,...,61.791442,17.516340,23.970588,43.218954,15.294118,20.500197,20.539583,21.721150,38.466315,8.758170
25,101030,København,9.951624,5.335176,18.023497,3.690394,32.978576,Ø,32.978576,49.384694,...,63.045428,12.488167,37.042161,44.454962,6.014709,27.915077,16.354288,14.795157,28.124138,8.279327
26,101032,København,11.406518,2.915952,10.377358,1.715266,30.445969,Ø,30.445969,50.312593,...,58.083065,28.937184,19.738017,42.185174,9.139625,12.104937,35.302623,19.355505,42.643678,11.655255
27,101033,København,14.869436,12.352862,20.173184,5.330808,19.672575,F,20.173184,51.380612,...,69.220655,18.166468,24.016687,45.093365,12.723480,27.141979,14.419176,20.172096,45.937873,4.410012
28,101034,København,15.865068,9.342469,21.623402,3.808143,22.703914,Ø,22.703914,50.790639,...,70.136446,22.873182,19.331120,45.232448,12.563251,24.490632,17.231494,20.088052,50.621670,6.586022
29,101035,København,17.333333,8.965517,16.804598,3.264368,21.931034,Ø,21.931034,50.526316,...,62.611108,21.432749,18.226121,44.571150,15.769981,17.529339,25.052502,22.767140,46.146024,9.249513
30,101036,København,19.805884,10.782530,19.502578,3.806491,18.168032,A,19.805884,50.198855,...,71.705296,22.852370,15.367483,47.271715,14.508431,20.383743,21.394677,23.839488,58.065735,6.092905
31,101040,København,14.675085,13.073606,21.050200,6.236526,17.600862,F,21.050200,49.557746,...,82.869228,24.222896,17.639626,46.525145,11.612333,27.937990,12.618770,20.503417,63.820739,2.312358
32,101041,København,15.921454,12.843306,19.782407,6.872761,17.686082,F,19.782407,52.102441,...,67.483998,17.722591,22.442500,45.957387,13.877522,24.034518,15.746753,20.121326,43.264809,5.707634
33,101042,København,15.294683,12.347854,19.170404,5.605381,17.729020,F,19.170404,51.362524,...,72.107979,21.260440,21.268877,45.634017,11.836666,26.666667,15.551983,20.171490,49.806094,4.640175
34,101043,København,13.222404,12.806418,19.878176,6.180360,19.046204,F,19.878176,51.048140,...,69.101228,14.375673,30.789626,45.273014,9.561687,28.150289,13.564547,18.342967,38.429420,4.018560
35,101044,København,15.032941,7.646237,17.927730,6.847674,17.847874,F,17.927730,50.265152,...,68.834292,20.284091,26.477273,43.948864,9.289773,19.945491,21.147175,21.271060,44.872847,7.433712
36,101046,København,17.870036,9.972924,18.163357,5.798736,16.538809,F,18.163357,48.322504,...,65.211558,18.034743,25.964726,45.192945,10.807585,17.051365,23.862159,22.578023,45.494505,8.871502
37,101047,København,14.333426,8.043418,16.392986,5.538547,24.018926,Ø,24.018926,51.614250,...,67.129204,21.347064,20.957417,43.960479,13.735040,22.790449,22.683535,18.692088,40.114527,7.598107
38,101048,København,14.240728,10.881735,18.946816,7.207838,18.299510,F,18.946816,50.328977,...,71.613979,18.621000,30.473186,43.893646,7.012168,28.689976,13.421111,16.685107,38.505961,4.596665
39,101049,København,10.703812,9.563376,20.397524,4.415119,28.136201,Ø,28.136201,50.789578,...,73.887527,20.065140,21.407422,52.842479,5.684959,38.030602,11.685587,12.524679,33.918009,3.375444
40,101050,København,9.773866,10.881773,19.578085,4.917286,25.163151,Ø,25.163151,50.408719,...,72.782599,17.651567,25.391689,51.311308,5.645436,37.791538,11.857585,11.589267,31.881777,4.359673
41,101051,København,12.089899,6.690778,17.282356,3.487471,29.527254,Ø,29.527254,50.008300,...,59.195212,14.998340,21.970452,49.584993,13.446215,18.455103,26.296332,22.006032,30.681983,11.777888
42,101052,København,9.070673,9.923947,19.569653,5.935819,26.785383,Ø,26.785383,50.070126,...,76.378592,17.369727,24.554968,51.785522,6.289783,39.722834,10.879420,10.180028,32.076339,3.355270
43,101053,København,11.194707,11.635750,17.421196,6.952912,19.743157,Ø,19.743157,50.901911,...,76.527024,20.727933,19.361725,52.182730,7.727612,38.506449,13.890020,12.070604,37.650602,3.885153
44,101054,København,11.396209,5.547850,17.984281,3.837263,30.073971,Ø,30.073971,46.374217,...,50.278649,10.854969,34.914951,44.471799,9.758281,25.872383,18.843470,15.852443,20.493359,10.519248
45,101055,København,10.474421,15.418691,15.790226,9.016862,13.975422,F,15.790226,47.560041,...,85.072345,15.559530,36.394992,45.088145,2.957333,39.140433,7.089049,11.505828,44.408523,1.520184
46,101056,København,11.528517,20.319392,15.498099,9.353612,13.825095,C,20.319392,50.819826,...,81.098563,17.820669,22.299260,50.173335,9.706737,41.658055,8.439545,13.365484,44.258598,2.286143
47,101058,København,7.862439,4.666326,17.680900,3.669138,35.310662,Ø,35.310662,52.177955,...,66.064343,17.941567,33.094290,43.505976,5.458167,29.734987,17.051625,12.197099,29.650679,8.492696
48,101059,København,11.072144,6.312625,17.860721,3.206413,30.435872,Ø,30.435872,49.477939,...,63.178102,19.613787,25.036488,45.335130,10.014595,20.958923,23.033787,19.304640,37.768849,8.701022
49,147001,Frederiksberg,18.582612,34.844115,8.652658,4.559813,15.231424,C,34.844115,51.942603,...,80.281516,20.860955,15.649912,46.656038,16.833096,38.131845,11.457456,14.374473,52.548876,3.121591
50,147002,Frederiksberg,20.515280,37.371523,7.729204,4.865013,13.800192,C,37.371523,51.062395,...,79.612367,18.929174,15.185497,46.500843,19.384486,38.650752,10.534510,15.256876,53.802817,2.588533
51,147003,Frederiksberg,19.528410,30.507946,8.715072,5.110626,17.575569,C,30.507946,52.379440,...,76.598552,18.400152,21.303768,46.190991,14.105089,38.524909,9.963472,13.942644,44.676782,2.344495
52,147004,Frederiksberg,20.431800,31.069380,8.669740,5.599910,16.552345,C,31.069380,53.299945,...,72.171752,18.372667,23.737651,42.508233,15.381449,35.366261,11.930586,14.725513,44.254974,3.835071
53,147005,Frederiksberg,21.851805,32.368851,7.434897,4.906278,16.580702,C,32.368851,52.082604,...,64.543385,16.898845,22.247112,44.102205,16.751838,26.712216,17.772473,18.184063,39.877691,7.917396
54,147006,Frederiksberg,22.522646,35.684875,6.533077,4.790008,15.797420,C,35.684875,54.424123,...,66.271451,15.612127,20.670621,39.479321,24.237930,25.449946,15.439245,22.492460,44.937276,4.588894
55,147007,Frederiksberg,22.364582,35.798554,7.547888,4.871242,14.372701,C,35.798554,52.459016,...,96.603746,15.628415,22.770071,45.384615,16.216898,33.982791,12.056176,16.655128,42.826688,3.997478

__Note__: because of mismatch in polling area groups this only has 56 rows and not the 58 as the other years

In [36]:
joined_df_2021_dem_2025_elec.to_csv(OUTPUT_DIR / "combined_2021_dem_2025_elec.csv", index=False)