# Feature Selection for Predicting the Election

This section concerns feature selection nescessary for answering the question: 

- Which demographic features best predict vote shares for major parties in Copenhagen and Frederiksberg, and can these patterns forecast the 2025 election winner?

It contains:

- Feature selection through correlation analysis
    - dropping features that are highly correlated
    
- Selecting top 10 features through ElasticNet model

In [35]:
#Imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import feature_select_predict_election as fs
from pathlib import Path

#Configuration
from feature_select_predict_election import EXCLUDE_COLS

CWD = Path.cwd()
PROJECT_ROOT = CWD.parents[3]

DATA_DIR = PROJECT_ROOT / "processed-data" / "combined"

OUTPUT_DIR = PROJECT_ROOT / "data-wrangling"/ "preprocessing"/ "predict_election"/"feature_selection"/ "pe_heatmaps"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [36]:
# Getting the combined data and conforming it into pandas dataframes.

# 2009
path = DATA_DIR / "pp_combined_2009.csv"

df_2009 = pd.read_csv(path, sep=',')

# 2013
path = DATA_DIR / "pp_combined_2013.csv"

df_2013 = pd.read_csv(path, sep=',')

# 2017 
path = DATA_DIR / "pp_combined_2017.csv"

df_2017 = pd.read_csv(path, sep=',')

# 2021 
path = DATA_DIR / "pp_combined_2021.csv"

df_2021 = pd.read_csv(path, sep=',')

In [31]:
#Correlation matrixes

corr_2009 = fs.correlation_matrix(df_2009, cols_to_exclude=EXCLUDE_COLS)
corr_2013 = fs.correlation_matrix(df_2013, cols_to_exclude=EXCLUDE_COLS)
corr_2017 = fs.correlation_matrix(df_2017, cols_to_exclude=EXCLUDE_COLS)
corr_2021 = fs.correlation_matrix(df_2021, cols_to_exclude=EXCLUDE_COLS)

### Correlation analysis

In [ ]:
print(fs.find_high_correlations(corr_2009, threshold=0.8))

save_path = OUTPUT_DIR / 'heat_map_2009'

fs.plot_heatmap(corr_2009,
    figsize=(18, 16),
    cmap="vlag",
    annot=True,
    fmt=".2f",
    title="Correlation Heatmap: 2009",
    save_path=save_path,)

                           Feature 1                                Feature 2  \
2                    Seniors_65_plus                Benefit type_Folkepension
4  Education_Primary_lower_secondary          Education_Long_higher_education
1        Socioeconomy_Top executives             Income_Gross income top20pct
7                 People_on_benefits        Education_Primary_lower_secondary
0         Housing tenure_People_Ejer  Housing type_People_Apartment buildings
5                Households_with_car               Housing tenure_People_Ejer
3  Education_Primary_lower_secondary              Housing tenure_People_Almen
6                 People_on_benefits              Housing tenure_People_Almen

   Correlation
2     0.998653
4    -0.929998
1     0.918553
7     0.856311
0    -0.852793
5     0.851521
3     0.835489
6     0.812440

c:\Users\Johanne Auener\Desktop\DAMIN A2\local-elections-damin2025\data-wrangling\preprocessing\predict_election\feature_selection\feature_select_predict_election.py:137: UserWarning: FigureCanvasPgf is non-interactive, and thus cannot be shown
  plt.show()

In [9]:
print(fs.find_high_correlations(corr_2013, threshold=0.8))

save_path = OUTPUT_DIR / 'heat_map_2013'

fs.plot_heatmap(corr_2013,
    figsize=(18, 16),
    cmap="vlag",
    annot=True,
    fmt=".2f",
    title="Correlation Heatmap: 2013",
    save_path=save_path,)

                            Feature 1                          Feature 2  \
3                     Seniors_65_plus          Benefit type_Folkepension
0         Socioeconomy_Top executives       Income_Gross income top20pct
6   Education_Primary_lower_secondary    Education_Long_higher_education
8                 Households_with_car         Housing tenure_People_Ejer
2             Socioeconomy_Unemployed        Socioeconomy_Top executives
7       Education_Vocational_training    Education_Long_higher_education
12                 People_on_benefits  Education_Primary_lower_secondary
10                 People_on_benefits        Housing tenure_People_Almen
9                 Households_with_car                        Youth_18_29
1             Socioeconomy_Unemployed       Income_Gross income top20pct
4     Education_Long_higher_education         Socioeconomy_Self-employed
5   Education_Primary_lower_secondary        Housing tenure_People_Almen
11                 People_on_benefits        Socioeconomy_Top executives

    Correlation
3      0.997751
0      0.913988
6     -0.906162
8      0.888683
2     -0.860631
7     -0.848294
12     0.842182
10     0.840228
9     -0.839502
1     -0.820721
4      0.801484
5      0.801301
11    -0.800961

c:\Users\Johanne Auener\Desktop\DAMIN A2\local-elections-damin2025\data-wrangling\preprocessing\predict_election\feature_selection\feature_select_predict_election.py:137: UserWarning: FigureCanvasPgf is non-interactive, and thus cannot be shown
  plt.show()

In [10]:
print(fs.find_high_correlations(corr_2017, threshold=0.8))

save_path = OUTPUT_DIR / 'heat_map_2017'

fs.plot_heatmap(corr_2017,
    figsize=(18, 16),
    cmap="vlag",
    annot=True,
    fmt=".2f",
    title="Correlation Heatmap: 2017",
    save_path=save_path,)

                            Feature 1                          Feature 2  \
3                     Seniors_65_plus          Benefit type_Folkepension
0         Socioeconomy_Top executives       Income_Gross income top20pct
6   Education_Primary_lower_secondary    Education_Long_higher_education
8                 Households_with_car         Housing tenure_People_Ejer
2             Socioeconomy_Unemployed        Socioeconomy_Top executives
7       Education_Vocational_training    Education_Long_higher_education
12                 People_on_benefits  Education_Primary_lower_secondary
10                 People_on_benefits        Housing tenure_People_Almen
9                 Households_with_car                        Youth_18_29
1             Socioeconomy_Unemployed       Income_Gross income top20pct
5   Education_Primary_lower_secondary        Housing tenure_People_Almen
4     Education_Long_higher_education         Socioeconomy_Self-employed
11                 People_on_benefits        Socioeconomy_Top executives

    Correlation
3      0.997745
0      0.913903
6     -0.906102
8      0.888556
2     -0.860476
7     -0.848513
12     0.842360
10     0.840062
9     -0.839783
1     -0.820684
5      0.801647
4      0.801481
11    -0.800637

c:\Users\Johanne Auener\Desktop\DAMIN A2\local-elections-damin2025\data-wrangling\preprocessing\predict_election\feature_selection\feature_select_predict_election.py:137: UserWarning: FigureCanvasPgf is non-interactive, and thus cannot be shown
  plt.show()

In [11]:
print(fs.find_high_correlations(corr_2021, threshold=0.8))

save_path = OUTPUT_DIR / 'heat_map_2021'

fs.plot_heatmap(corr_2021,
    figsize=(18, 16),
    cmap="vlag",
    annot=True,
    fmt=".2f",
    title="Correlation Heatmap: 2021",
    save_path=save_path,)

                           Feature 1                          Feature 2  \
1                    Seniors_65_plus          Benefit type_Folkepension
0        Socioeconomy_Top executives       Income_Gross income top20pct
3  Education_Primary_lower_secondary    Education_Long_higher_education
8                 People_on_benefits  Education_Primary_lower_secondary
6                 People_on_benefits        Housing tenure_People_Almen
4      Education_Vocational_training    Education_Long_higher_education
2  Education_Primary_lower_secondary        Housing tenure_People_Almen
7                 People_on_benefits        Socioeconomy_Top executives
5                Households_with_car         Housing tenure_People_Ejer

   Correlation
1     0.998735
0     0.932412
3    -0.890275
8     0.879353
6     0.871941
4    -0.868486
2     0.864529
7    -0.821593
5     0.811659

c:\Users\Johanne Auener\Desktop\DAMIN A2\local-elections-damin2025\data-wrangling\preprocessing\predict_election\feature_selection\feature_select_predict_election.py:137: UserWarning: FigureCanvasPgf is non-interactive, and thus cannot be shown
  plt.show()

### Conclusion from correlation analysis

From the correlation analysis it is evident that some feature pairs are very highly correlated across election years. Here especially:

- Seniors_65_plus and Benefit type_Folkepension (0.997-0.999)
- Socioeconomy_Top executives and Income_Gross income top20pct (0.91-0.93)
- Housing tenure_People_Ejer and Households_with_car(0.81-0.89)

Common for the pairs are that they all capture the same underlying things. Therefor I will drop the features: 'Benefit type_Folkepension', 'Income_Gross income top20pct', 'Households_with_car'.

The other correlated features, they are still very correlated, however they correlation does not capture the same thing or if it does it is because it is negative and it captures that when you have fewer of one group you often have more of another.
These pairs are the following:      
- Education_Primary_lower_secondary & Education_Long_higher_education   
- People_on_benefits & Education_Primary_lower_secondary   
- People_on_benefits & Housing tenure_People_Almen   
- Education_Vocational_training & Education_Long_higher_education   
- Education_Primary_lower_secondary & Housing tenure_People_Almen   
- People_on_benefits & Socioeconomy_Top executives

In [32]:
#Dropping highly correlated 
df_2009 = fs.after_corr_drop(df_2009)
df_2013 = fs.after_corr_drop(df_2013)
df_2017 = fs.after_corr_drop(df_2017)
df_2021 = fs.after_corr_drop(df_2021)

In [13]:
print(f"Coloumns in the df {df_2009.columns}")

Coloumns in the df Index(['Gruppe', 'Municipality', 'A_vote_share', 'C_vote_share',
       'F_vote_share', 'V_vote_share', 'Ø_vote_share', 'winning_party',
       'winning_votes', 'Sex_Female',
       'Housing type_People_Apartment buildings',
       'Housing tenure_People_Almen', 'Housing tenure_People_Andel',
       'Housing tenure_People_Ejer', 'Housing tenure_People_Private rental',
       'Socioeconomy_Self-employed', 'Socioeconomy_Top executives',
       'Socioeconomy_Unemployed', 'Income_Median_normalized', 'Children_0_17',
       'Youth_18_29', 'WorkingAge_30_64', 'Seniors_65_plus',
       'Education_Long_higher_education', 'Education_Primary_lower_secondary',
       'Education_Vocational_training', 'People_on_benefits'],
      dtype='object')

In [33]:
#Align all columns first (adds missing columns as NaN)
df_combined = fs.align_columns_across_years(df_2009, df_2013, df_2017, df_2021)

Total unique columns across all years: 28

Year 2009: Adding 1 missing columns

Final combined dataframe: (232, 29)
Missing values by column (top 10):
Series([], dtype: int64)

In [16]:
df_combined

,Gruppe,Municipality,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,winning_party,winning_votes,Sex_Female,...,Children_0_17,Youth_18_29,WorkingAge_30_64,Seniors_65_plus,Education_Long_higher_education,Education_Primary_lower_secondary,Education_Vocational_training,People_on_benefits,Crime_Number of arrests,year
0,101001,København,26.298171,9.436795,22.805637,11.911655,9.991970,A,26.298171,51.910675,...,17.215953,23.857093,49.872148,9.054807,26.513482,13.910419,16.042891,3.946880,0.000000,2009
1,101002,København,26.647399,11.705202,18.208092,15.520231,6.213873,A,26.647399,54.290625,...,17.783948,20.230067,45.074706,16.911279,22.756513,17.626246,18.977163,5.169906,0.000000,2009
2,101003,København,26.259451,9.526297,21.981002,11.389767,10.096638,A,26.259451,52.042660,...,18.347493,21.835630,51.041155,8.775722,28.505771,13.118339,15.698604,3.606073,0.000000,2009
3,101005,København,30.259319,8.071313,21.604538,10.551053,8.752026,A,30.259319,51.836118,...,15.444988,24.452765,47.076613,13.025634,19.986375,19.288087,21.042323,5.349942,0.000000,2009
4,101006,København,30.534215,8.772557,19.689119,10.988029,8.308022,A,30.534215,51.826389,...,17.129131,23.043154,48.090781,11.736934,20.799600,18.830585,20.799600,6.361302,0.000000,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,147003,Frederiksberg,15.967291,37.508070,5.186142,5.917796,19.604046,C,37.508070,52.379440,...,18.400152,21.303768,46.190991,14.105089,38.524909,9.963472,13.942644,2.344495,0.165195,2021
228,147004,Frederiksberg,15.880391,39.063617,5.086967,7.052657,17.286157,C,39.063617,53.299945,...,18.372667,23.737651,42.508233,15.381449,35.366261,11.930586,14.725513,3.835071,0.315587,2021
229,147005,Frederiksberg,20.443925,37.798546,4.802700,5.763240,17.458463,C,37.798546,52.082604,...,16.898845,22.247112,44.102205,16.751838,26.712216,17.772473,18.184063,7.917396,0.721036,2021
230,147006,Frederiksberg,19.147440,42.473270,3.798537,5.233540,15.855374,C,42.473270,54.424123,...,15.612127,20.670621,39.479321,24.237930,25.449946,15.439245,22.492460,4.588894,0.304828,2021
231,147007,Frederiksberg,17.304597,42.537261,4.569309,5.492968,16.499895,C,42.537261,52.459016,...,15.628415,22.770071,45.384615,16.216898,33.982791,12.056176,16.655128,3.997478,0.424548,2021

In [34]:
corr_combined = fs.correlation_matrix(df_combined, cols_to_exclude=EXCLUDE_COLS)
print(fs.find_high_correlations(corr_combined, threshold=0.8))

save_path = OUTPUT_DIR / 'heat_map_combined'

fs.plot_heatmap(corr_combined,
    figsize=(18, 16),
    cmap="vlag",
    annot=True,
    fmt=".2f",
    title="Correlation Heatmap: 2009-2021",
    save_path=save_path,)

                           Feature 1                          Feature 2  \
0  Education_Primary_lower_secondary    Education_Long_higher_education
1      Education_Vocational_training    Education_Long_higher_education
3                 People_on_benefits  Education_Primary_lower_secondary
2                 People_on_benefits        Housing tenure_People_Almen

   Correlation
0    -0.906817
1    -0.832282
3     0.830443
2     0.802169

c:\Users\Johanne Auener\Desktop\DAMIN A2\local-elections-damin2025\data-wrangling\preprocessing\predict_election\feature_selection\feature_select_predict_election.py:137: UserWarning: FigureCanvasPgf is non-interactive, and thus cannot be shown
  plt.show()

In [17]:
fs.validate_combined_data(df_combined)

VALIDATION CHECKS
============================================================
✓ No duplicate Gruppe-Year combinations
✓ Year 2009: 58 rows
✓ Year 2013: 58 rows
✓ Year 2017: 58 rows
✓ Year 2021: 58 rows

Missing values by year:
  2009: 0.00% missing
  2013: 0.00% missing
  2017: 0.00% missing
  2021: 0.00% missing

Column data types:
float64    25
int64       2
object      2
Name: count, dtype: int64

True

In [21]:
fs.check_preprocessing(df_combined)

============================================================
Preprocess validation
============================================================

1. Missing Values:
No missing values

2. Infinite Values:
No infinite values

3. Feature Scales (sample of numeric columns):
             Gruppe  A_vote_share  C_vote_share  F_vote_share  V_vote_share
mean  106578.724138     25.253509     11.165148     12.360709      8.513341
std    15009.118032      6.866226     10.860054      5.877415      3.361574
min   101001.000000     10.812731      1.198257      3.540305      1.945796
max   147007.000000     52.377807     43.650000     28.842643     23.847926

If scales vary widely (e.g., 0-1 vs 0-10000), standardize features

4. Low Variance Features:
All features have reasonable variance!

6. Duplicate Rows:
No duplicate rows

------------------------------------------------------------

True

In [22]:
regression_results = fs.feature_selection_regression(df_combined)

------------------------------------------------------------
PATH 2: REGRESSION FEATURE SELECTION
------------------------------------------------------------

============================================================
PARTY: A
============================================================

--- Year: 2009 ---
R² score: 0.851
Features selected: 14
Top 5 features:
                              feature  importance
17                 People_on_benefits    3.536661
15  Education_Primary_lower_secondary    2.900960
14    Education_Long_higher_education    2.714115
2         Housing tenure_People_Almen    2.622520
4          Housing tenure_People_Ejer    1.147350

--- Year: 2013 ---
R² score: 0.847
Features selected: 16
Top 5 features:
                                    feature  importance
14          Education_Long_higher_education    6.953699
17                       People_on_benefits    6.256081
4                Housing tenure_People_Ejer    5.126666
16            Education_Vocational_training    3.049277
1   Housing type_People_Apartment buildings    2.385324

--- Year: 2017 ---
R² score: 0.451
Features selected: 4
Top 5 features:
                                    feature  importance
14          Education_Long_higher_education    1.728907
1   Housing type_People_Apartment buildings    0.809917
15        Education_Primary_lower_secondary    0.318928
0                                Sex_Female    0.057344
10                            Children_0_17    0.000000

--- Year: 2021 ---
R² score: 0.855
Features selected: 18
Top 5 features:
                                    feature  importance
16            Education_Vocational_training    1.158869
14          Education_Long_higher_education    0.815367
1   Housing type_People_Apartment buildings    0.753865
11                              Youth_18_29    0.542117
6                Socioeconomy_Self-employed    0.449302

--- All Years Pooled (2009-2021) ---

R² score: 0.685
Top 10 features:
                                    feature  importance
14          Education_Long_higher_education    2.353480
16            Education_Vocational_training    1.528579
15        Education_Primary_lower_secondary    1.390690
1   Housing type_People_Apartment buildings    1.044841
10                            Children_0_17    0.974691
6                Socioeconomy_Self-employed    0.962716
9                  Income_Median_normalized    0.862558
8                   Socioeconomy_Unemployed    0.837026
18                  Crime_Number of arrests    0.793736
17                       People_on_benefits    0.625201

============================================================
PARTY: V
============================================================

--- Year: 2009 ---
R² score: 0.206
Features selected: 10
Top 5 features:
                                    feature  importance
4                Housing tenure_People_Ejer    0.162917
17                       People_on_benefits    0.142096
1   Housing type_People_Apartment buildings    0.140389
5      Housing tenure_People_Private rental    0.134183
3               Housing tenure_People_Andel    0.125073

--- Year: 2013 ---
R² score: 0.405
Features selected: 6
Top 5 features:
                                 feature  importance
4             Housing tenure_People_Ejer    0.703405
8                Socioeconomy_Unemployed    0.488410
7            Socioeconomy_Top executives    0.272374
12                      WorkingAge_30_64    0.179586
5   Housing tenure_People_Private rental    0.133998

--- Year: 2017 ---
R² score: 0.458
Features selected: 5
Top 5 features:
                                 feature  importance
8                Socioeconomy_Unemployed    0.528371
4             Housing tenure_People_Ejer    0.409403
7            Socioeconomy_Top executives    0.344978
5   Housing tenure_People_Private rental    0.109435
17                    People_on_benefits    0.074527

--- Year: 2021 ---
R² score: 0.769
Features selected: 15
Top 5 features:
                              feature  importance
7         Socioeconomy_Top executives    2.084898
15  Education_Primary_lower_secondary    1.451503
8             Socioeconomy_Unemployed    1.319456
11                        Youth_18_29    1.164751
13                    Seniors_65_plus    1.158725

--- All Years Pooled (2009-2021) ---

R² score: 0.495
Top 10 features:
                                    feature  importance
7               Socioeconomy_Top executives    3.816696
14          Education_Long_higher_education    2.601650
17                       People_on_benefits    1.675684
13                          Seniors_65_plus    1.363521
1   Housing type_People_Apartment buildings    1.157017
10                            Children_0_17    1.131987
2               Housing tenure_People_Almen    0.805415
0                                Sex_Female    0.590888
8                   Socioeconomy_Unemployed    0.583452
11                              Youth_18_29    0.582263

============================================================
PARTY: C
============================================================

--- Year: 2009 ---
R² score: 0.417
Features selected: 16
Top 5 features:
                                    feature  importance
13                          Seniors_65_plus    1.431746
7               Socioeconomy_Top executives    1.011805
0                                Sex_Female    0.987252
8                   Socioeconomy_Unemployed    0.909687
1   Housing type_People_Apartment buildings    0.664214

--- Year: 2013 ---
R² score: 0.364
Features selected: 17
Top 5 features:
                        feature  importance
13              Seniors_65_plus    1.227882
0                    Sex_Female    0.847683
7   Socioeconomy_Top executives    0.610041
8       Socioeconomy_Unemployed    0.495019
11                  Youth_18_29    0.449659

--- Year: 2017 ---
R² score: 0.356
Features selected: 18
Top 5 features:
                        feature  importance
13              Seniors_65_plus    1.178562
0                    Sex_Female    0.826377
7   Socioeconomy_Top executives    0.592686
8       Socioeconomy_Unemployed    0.508476
11                  Youth_18_29    0.462508

--- Year: 2021 ---
R² score: 0.679
Features selected: 18
Top 5 features:
                                    feature  importance
13                          Seniors_65_plus    2.403194
1   Housing type_People_Apartment buildings    1.704470
12                         WorkingAge_30_64    1.365131
8                   Socioeconomy_Unemployed    1.343050
7               Socioeconomy_Top executives    1.298530

--- All Years Pooled (2009-2021) ---

R² score: 0.673
Top 10 features:
                                    feature  importance
1   Housing type_People_Apartment buildings    6.751534
14          Education_Long_higher_education    6.157574
13                          Seniors_65_plus    5.689180
4                Housing tenure_People_Ejer    5.538740
17                       People_on_benefits    4.426141
6                Socioeconomy_Self-employed    3.215436
7               Socioeconomy_Top executives    2.998958
8                   Socioeconomy_Unemployed    2.994082
15        Education_Primary_lower_secondary    2.870884
5      Housing tenure_People_Private rental    2.049663

============================================================
PARTY: F
============================================================

--- Year: 2009 ---
R² score: 0.719
Features selected: 5
Top 5 features:
                                    feature  importance
13                          Seniors_65_plus    1.189615
3               Housing tenure_People_Andel    1.169459
7               Socioeconomy_Top executives    0.594265
11                              Youth_18_29    0.210873
1   Housing type_People_Apartment buildings    0.067100

--- Year: 2013 ---
R² score: 0.912
Features selected: 16
Top 5 features:
                              feature  importance
17                 People_on_benefits    2.680898
15  Education_Primary_lower_secondary    2.603485
2         Housing tenure_People_Almen    1.145329
7         Socioeconomy_Top executives    0.911307
18            Crime_Number of arrests    0.749462

--- Year: 2017 ---
R² score: 0.665
Features selected: 11
Top 5 features:
                                    feature  importance
1   Housing type_People_Apartment buildings    1.105416
3               Housing tenure_People_Andel    0.877894
15        Education_Primary_lower_secondary    0.541414
17                       People_on_benefits    0.507564
13                          Seniors_65_plus    0.399297

--- Year: 2021 ---
R² score: 0.793
Features selected: 10
Top 5 features:
                                    feature  importance
1   Housing type_People_Apartment buildings    1.677313
13                          Seniors_65_plus    1.460145
4                Housing tenure_People_Ejer    0.790773
9                  Income_Median_normalized    0.722729
3               Housing tenure_People_Andel    0.500291

--- All Years Pooled (2009-2021) ---

R² score: 0.900
Top 10 features:
                                 feature  importance
8                Socioeconomy_Unemployed    4.530065
7            Socioeconomy_Top executives    3.006996
14       Education_Long_higher_education    1.644999
13                       Seniors_65_plus    1.565121
16         Education_Vocational_training    0.977732
6             Socioeconomy_Self-employed    0.921381
17                    People_on_benefits    0.882223
18               Crime_Number of arrests    0.852128
3            Housing tenure_People_Andel    0.840168
5   Housing tenure_People_Private rental    0.500566

============================================================
PARTY: Ø
============================================================

--- Year: 2009 ---
R² score: 0.595
Features selected: 14
Top 5 features:
                          feature  importance
13                Seniors_65_plus    0.578422
3     Housing tenure_People_Andel    0.509221
8         Socioeconomy_Unemployed    0.504510
16  Education_Vocational_training    0.499883
6      Socioeconomy_Self-employed    0.306646

--- Year: 2013 ---
R² score: 0.721
Features selected: 19
Top 5 features:
                        feature  importance
8       Socioeconomy_Unemployed    1.060004
7   Socioeconomy_Top executives    1.021591
17           People_on_benefits    0.669893
13              Seniors_65_plus    0.648976
4    Housing tenure_People_Ejer    0.648299

--- Year: 2017 ---
R² score: 0.841
Features selected: 12
Top 5 features:
                          feature  importance
8         Socioeconomy_Unemployed    1.901999
7     Socioeconomy_Top executives    1.475632
16  Education_Vocational_training    0.972630
6      Socioeconomy_Self-employed    0.890882
13                Seniors_65_plus    0.770410

--- Year: 2021 ---
R² score: 0.824
Features selected: 10
Top 5 features:
                          feature  importance
8         Socioeconomy_Unemployed    3.275832
7     Socioeconomy_Top executives    2.339416
6      Socioeconomy_Self-employed    2.188945
16  Education_Vocational_training    0.841491
12               WorkingAge_30_64    0.673848

--- All Years Pooled (2009-2021) ---

R² score: 0.744
Top 10 features:
                                    feature  importance
7               Socioeconomy_Top executives    2.658934
14          Education_Long_higher_education    2.238972
8                   Socioeconomy_Unemployed    1.809698
5      Housing tenure_People_Private rental    1.611859
16            Education_Vocational_training    1.593603
18                  Crime_Number of arrests    1.076073
2               Housing tenure_People_Almen    0.971486
1   Housing type_People_Apartment buildings    0.680197
15        Education_Primary_lower_secondary    0.633187
12                         WorkingAge_30_64    0.549545

Features Important Across Multiple Parties:
                                    feature  n_parties        parties  \
0                        People_on_benefits          5  A, V, C, F, Ø
5                           Seniors_65_plus          5  A, V, C, F, Ø
2           Education_Long_higher_education          5  A, V, C, F, Ø
8                   Socioeconomy_Unemployed          5  A, V, C, F, Ø
14              Socioeconomy_Top executives          5  A, V, C, F, Ø
6   Housing type_People_Apartment buildings          5  A, V, C, F, Ø
1         Education_Primary_lower_secondary          5  A, V, C, F, Ø
4                Housing tenure_People_Ejer          5  A, V, C, F, Ø
16            Education_Vocational_training          5  A, V, C, F, Ø
3               Housing tenure_People_Almen          5  A, V, C, F, Ø
10               Socioeconomy_Self-employed          5  A, V, C, F, Ø
7                          WorkingAge_30_64          5  A, V, C, F, Ø
17              Housing tenure_People_Andel          5  A, V, C, F, Ø
15                              Youth_18_29          5  A, V, C, F, Ø
12     Housing tenure_People_Private rental          5  A, V, C, F, Ø

    mean_importance
0          0.797467
5          0.732765
2          0.730851
8          0.716725
14         0.667376
6          0.614318
1          0.586294
4          0.563595
16         0.375177
3          0.347224
10         0.318715
7          0.262324
17         0.255558
15         0.254085
12         0.248406

In [23]:
#Select final features
final_features = fs.select_top_features(regression_results=regression_results, n_features=10)

------------------------------------------------------------
RECOMMENDED TOP 10 FEATURES
------------------------------------------------------------

From Regression (Cross-Party Importance):
                                    feature  n_parties        parties  \
0                        People_on_benefits          5  A, V, C, F, Ø
5                           Seniors_65_plus          5  A, V, C, F, Ø
2           Education_Long_higher_education          5  A, V, C, F, Ø
8                   Socioeconomy_Unemployed          5  A, V, C, F, Ø
14              Socioeconomy_Top executives          5  A, V, C, F, Ø
6   Housing type_People_Apartment buildings          5  A, V, C, F, Ø
1         Education_Primary_lower_secondary          5  A, V, C, F, Ø
4                Housing tenure_People_Ejer          5  A, V, C, F, Ø
16            Education_Vocational_training          5  A, V, C, F, Ø
3               Housing tenure_People_Almen          5  A, V, C, F, Ø

    mean_importance
0          0.797467
5          0.732765
2          0.730851
8          0.716725
14         0.667376
6          0.614318
1          0.586294
4          0.563595
16         0.375177
3          0.347224

FINAL RECOMMENDED FEATURES (10 total):
1. Education_Long_higher_education
2. Education_Primary_lower_secondary
3. Education_Vocational_training
4. Housing tenure_People_Almen
5. Housing tenure_People_Ejer
6. Housing type_People_Apartment buildings
7. People_on_benefits
8. Seniors_65_plus
9. Socioeconomy_Top executives
10. Socioeconomy_Unemployed

In [25]:
keep_cols = [
    'Gruppe','year', 'winning_party','A_vote_share', 'C_vote_share', 'F_vote_share',
    'V_vote_share', 'Ø_vote_share'
]

selected_features = [
    'Education_Long_higher_education',
    'Education_Primary_lower_secondary',
    'Education_Vocational_training',
    'Housing tenure_People_Almen',
    'Housing tenure_People_Ejer',
    'Housing type_People_Apartment buildings',
    'People_on_benefits',
    'Seniors_65_plus',
    'Socioeconomy_Top executives',
    'Socioeconomy_Unemployed'
]

cols_final = [*keep_cols, *selected_features]

In [26]:
# double check that the columns exist
cols_final_existing = [c for c in cols_final if c in df_combined.columns]

df_combined_features = df_combined[cols_final_existing]

In [27]:
df_combined_features

,Gruppe,year,winning_party,A_vote_share,C_vote_share,F_vote_share,V_vote_share,Ø_vote_share,Education_Long_higher_education,Education_Primary_lower_secondary,Education_Vocational_training,Housing tenure_People_Almen,Housing tenure_People_Ejer,Housing type_People_Apartment buildings,People_on_benefits,Seniors_65_plus,Socioeconomy_Top executives,Socioeconomy_Unemployed
0,101001,2009,A,26.298171,9.436795,22.805637,11.911655,9.991970,26.513482,13.910419,16.042891,9.872878,16.013522,98.631646,3.946880,9.054807,1.897272,1.062511
1,101002,2009,A,26.647399,11.705202,18.208092,15.520231,6.213873,22.756513,17.626246,18.977163,12.755462,28.935870,86.050509,5.169906,16.911279,1.799866,1.061115
2,101003,2009,A,26.259451,9.526297,21.981002,11.389767,10.096638,28.505771,13.118339,15.698604,2.679059,17.802022,97.494376,3.606073,8.775722,2.011154,0.940405
3,101005,2009,A,30.259319,8.071313,21.604538,10.551053,8.752026,19.986375,19.288087,21.042323,12.462385,16.051376,95.312500,5.349942,13.025634,1.100878,1.223198
4,101006,2009,A,30.534215,8.772557,19.689119,10.988029,8.308022,20.799600,18.830585,20.799600,13.159687,20.999319,89.704299,6.361302,11.736934,1.385296,1.251773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,147003,2021,C,15.967291,37.508070,5.186142,5.917796,19.604046,38.524909,9.963472,13.942644,3.446724,28.869690,97.255226,2.344495,14.105089,2.529715,1.786055
228,147004,2021,C,15.880391,39.063617,5.086967,7.052657,17.286157,35.366261,11.930586,14.725513,12.504348,43.695652,86.278814,3.835071,15.381449,2.501196,1.872480
229,147005,2021,C,20.443925,37.798546,4.802700,5.763240,17.458463,26.712216,17.772473,18.184063,33.018613,40.774211,88.337417,7.917396,16.751838,1.971831,2.074888
230,147006,2021,C,19.147440,42.473270,3.798537,5.233540,15.855374,25.449946,15.439245,22.492460,20.554707,38.547420,91.291811,4.588894,24.237930,2.064580,1.668181
231,147007,2021,C,17.304597,42.537261,4.569309,5.492968,16.499895,33.982791,12.056176,16.655128,8.704083,29.237077,93.404792,3.997478,16.216898,2.042186,1.975091

In [28]:
# saving the combined dataframe with selected features to as a csv

path = DATA_DIR / "combined_features_2009_2021.csv"

df_combined_features.to_csv( path , index=False)